# Collapse Revenue

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Docs/Revenue_Budget_&_Financial_Plan_--_Exec_Adpt_Prel_20260605.xlsx", sheet_name="Data")

In [3]:
print(df.describe())

df.head()

        Fiscal Year     FPS Group  Agency Number  Revenue Category  \
count  55131.000000  55191.000000   55191.000000      55191.000000
mean    2021.011173     30.142052     490.815894         25.014024
std        2.922871      7.540532     386.908807          5.265179
min     2017.000000      1.000000       2.000000         20.000000
25%     2018.000000     24.000000      56.000000         22.000000
50%     2021.000000     33.000000     806.000000         25.000000
75%     2024.000000     35.000000     841.000000         26.000000
max     2026.000000     40.000000     945.000000         90.000000

       Revenue Class Code  Revenue Source  Adopted Budget Amount  \
count        55191.000000    55191.000000           5.517000e+04
mean           170.528474    16950.054339           5.469299e+07
std            158.375732    18448.568716           6.396431e+08
min              1.000000        1.000000          -2.100000e+09
25%             13.000000      595.000000           0.000000e+00
50%            210.000000     8016.000000           1.231200e+05
75%            293.000000    29976.000000           2.221256e+06
max            437.000000    99995.000000           1.879400e+10

       Current Modified Budget Amount        Yr1_FY  Year 1 Revenue Amount  \
count                    5.515600e+04  55191.000000           5.519100e+04
mean                     5.794437e+07   2020.937055           5.838243e+07
std                      6.509292e+08      3.029071           6.566756e+08
min                     -2.486000e+09   2016.000000          -2.500000e+09
25%                      1.090000e+05   2018.000000           1.100000e+05
50%                      5.520530e+05   2021.000000           5.630000e+05
75%                      3.707703e+06   2024.000000           3.780045e+06
max                      1.997400e+10   2026.000000           2.002200e+10

       Year 2 Revenue Amount  Year 3 Revenue Amount  Year 4 Revenue Amount  \
count           5.519100e+04           5.519100e+04           5.519100e+04
mean            5.672151e+07           5.756559e+07           5.881675e+07
std             6.717684e+08           6.946848e+08           7.183825e+08
min            -2.536000e+09          -2.628000e+09          -2.719000e+09
25%             0.000000e+00           0.000000e+00           0.000000e+00
50%             1.161960e+05           8.400000e+04           6.500000e+04
75%             2.200000e+06           2.049779e+06           2.000000e+06
max             2.098500e+10           2.149400e+10           2.181800e+10

       Year 5 Revenue Amount
count           5.519100e+04
mean            5.996403e+07
std             7.400092e+08
min            -2.810000e+09
25%             0.000000e+00
50%             6.000000e+04
75%             1.998218e+06
max             2.247000e+10

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 1 Revenue Amount,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount,Year 5 Revenue Amount
0,2026 05 12,2026.0,City Funds,13,All Other,2,Mayoralty,20,TAXES,5,...,REFUNDS OF ALL OTHER TAXES,REFUNDS OF ALL OTHER TAXES,-52000000.0,-52000000.0,2026,-52000000,-52000000,-52000000,-52000000,-52000000
1,2026 05 12,2026.0,City Funds,13,All Other,2,Mayoralty,20,TAXES,5,...,TAX ON HORSE RACE ADMISSIONS,TAX ON HORSE RACE ADMISSIONS,50000.0,50000.0,2026,50000,50000,50000,50000,50000
2,2026 05 12,2026.0,City Funds,13,All Other,2,Mayoralty,20,TAXES,5,...,Medical Marijuana Excise Tax,MEDICAL MARIJUANA EXCISE TAX,600000.0,600000.0,2026,600000,600000,600000,600000,600000
3,2026 05 12,2026.0,City Funds,13,All Other,2,Mayoralty,20,TAXES,5,...,OFF TRACK BETTING - SURTAX,OFF TRACK BETTING - SURCHARGE,760000.0,760000.0,2026,760000,760000,760000,760000,760000
4,2026 05 12,2026.0,City Funds,13,All Other,2,Mayoralty,20,TAXES,5,...,BEER + LIQUOR EXCISE TAX,BEER & LIQUOR TAX,25000000.0,24000000.0,2026,24000000,25000000,25000000,25000000,25000000

In [4]:
for c in df.columns:
    print(f"'{c}',")

'Publication Date',
'Fiscal Year',
'Fundind Source Name',
'FPS Group',
'FPS Group Name',
'Agency Number',
'Agency Name',
'Revenue Category',
'Revenue Category Name',
'Revenue Class Code',
'Revenue Class Name',
'Budget Code',
'Revenue Source',
'Revenue Source Name',
'Revenue Structure Description',
'Adopted Budget Amount',
'Current Modified Budget Amount',
'Yr1_FY',
'Year 1 Revenue Amount',
'Year 2 Revenue Amount',
'Year 3 Revenue Amount',
'Year 4 Revenue Amount',
'Year 5 Revenue Amount',

In [5]:
date_columns = [
'Publication Date',
'Fiscal Year',
]

catagory_columns = [
'Agency Number',
'Agency Name',
'Fundind Source Name',
# 'Revenue Category',
# 'Revenue Category Name',
# 'Revenue Class Code',
# 'Revenue Class Name',
# 'Revenue Source',
# 'Revenue Source Name',
]

value_columns = [
'Adopted Budget Amount',
'Current Modified Budget Amount',
# 'Year 1 Revenue Amount',
'Year 2 Revenue Amount',
# 'Year 3 Revenue Amount',
# 'Year 4 Revenue Amount',
# 'Year 5 Revenue Amount',
]

target_columns = date_columns + catagory_columns + value_columns
target_columns

['Publication Date',
 'Fiscal Year',
 'Agency Number',
 'Agency Name',
 'Fundind Source Name',
 'Adopted Budget Amount',
 'Current Modified Budget Amount',
 'Year 2 Revenue Amount']

In [6]:
print(df.columns)
print(df.dtypes)

Index(['Publication Date', 'Fiscal Year', 'Fundind Source Name', 'FPS Group',
       'FPS Group Name', 'Agency Number', 'Agency Name', 'Revenue Category',
       'Revenue Category Name', 'Revenue Class Code', 'Revenue Class Name',
       'Budget Code', 'Revenue Source', 'Revenue Source Name',
       'Revenue Structure Description', 'Adopted Budget Amount',
       'Current Modified Budget Amount', 'Yr1_FY', 'Year 1 Revenue Amount',
       'Year 2 Revenue Amount', 'Year 3 Revenue Amount',
       'Year 4 Revenue Amount', 'Year 5 Revenue Amount'],
      dtype='str')
Publication Date                      str
Fiscal Year                       float64
Fundind Source Name                   str
FPS Group                           int64
FPS Group Name                        str
Agency Number                       int64
Agency Name                           str
Revenue Category                    int64
Revenue Category Name                 str
Revenue Class Code                  int64
Revenue Class Name                    str
Budget Code                           str
Revenue Source                      int64
Revenue Source Name                   str
Revenue Structure Description         str
Adopted Budget Amount             float64
Current Modified Budget Amount    float64
Yr1_FY                              int64
Year 1 Revenue Amount               int64
Year 2 Revenue Amount               int64
Year 3 Revenue Amount               int64
Year 4 Revenue Amount               int64
Year 5 Revenue Amount               int64
dtype: object

In [7]:
new_df = df[target_columns].copy()

new_df = new_df.sort_values(by=['Agency Number',"Publication Date"], ascending=[True,False])

# df['Fiscal Year'] = df['Fiscal Year'].astype("int64")

new_df["Publication Date"].unique()

<StringArray>
['2026 05 12', '2026 02 17', '2025 06 30', '2025 05 01', '2025 01 16',
 '2024 07 02', '2024 04 24', '2024 01 16', '2023 06 30', '2023 04 26',
 '2023 01 12', '2022 06 14', '2022 04 26', '2022 02 16', '2021 06 30',
 '2021 04 26', '2021 01 14', '2020 06 30', '2020 04 16', '2020 01 16',
  '2019 2 07', '2019 06 19', '2019 04 24',  '2018 6 14',  '2018 4 26',
  '2018 2 01',   '20170124',  '2017 6 06',  '2017 4 26', '2016 06 14',
 '2016 04 26']
Length: 31, dtype: str

In [8]:
new_df = new_df[new_df["Publication Date"].isin(['2026 05 12', '2026 02 17'])]
# new_df = new_df.sort_values(by=['Agency Number', 'Revenue Category','Revenue Class Code','Revenue Source',"Publication Date"], ascending=[True,True,True,True,False])

new_df = new_df.reset_index(drop=True)
new_df

,Publication Date,Fiscal Year,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,Year 2 Revenue Amount
0,2026 05 12,2026.0,2,Mayoralty,City Funds,-52000000.0,-52000000.0,-52000000
1,2026 05 12,2026.0,2,Mayoralty,City Funds,50000.0,50000.0,50000
2,2026 05 12,2026.0,2,Mayoralty,City Funds,600000.0,600000.0,600000
3,2026 05 12,2026.0,2,Mayoralty,City Funds,760000.0,760000.0,760000
4,2026 05 12,2026.0,2,Mayoralty,City Funds,25000000.0,24000000.0,25000000
...,...,...,...,...,...,...,...,...
3477,2026 02 17,2026.0,943,Public Administrator-Kings County,City Funds,804000.0,804000.0,804000
3478,2026 05 12,2026.0,944,Public Administrator-Queens County,City Funds,1060000.0,1060000.0,1060000
3479,2026 02 17,2026.0,944,Public Administrator-Queens County,City Funds,1060000.0,1060000.0,1060000
3480,2026 05 12,2026.0,945,Public Administrator-Richmond County,City Funds,65000.0,65000.0,65000
3481,2026 02 17,2026.0,945,Public Administrator-Richmond County,City Funds,65000.0,65000.0,65000

## Groupings

### Agency By Funding Source ("Fundind Source Name")

In [9]:
base_df = new_df[catagory_columns].drop_duplicates().reset_index(drop=True).copy()

# base_df[value_columns] = 0

base_df

,Agency Number,Agency Name,Fundind Source Name
0,2,Mayoralty,City Funds
1,2,Mayoralty,Intra-City
2,2,Mayoralty,Other Categorical Grants
3,2,Mayoralty,Inter Fund Agreements
4,2,Mayoralty,Federal Grants
...,...,...,...
232,941,Public Administrator-New York County,City Funds
233,942,Public Administrator-Bronx County,City Funds
234,943,Public Administrator-Kings County,City Funds
235,944,Public Administrator-Queens County,City Funds
236,945,Public Administrator-Richmond County,City Funds

In [10]:
grouped_df_1 = new_df.groupby(date_columns + catagory_columns, as_index=False)[value_columns].sum().copy()
grouped_df_1 = grouped_df_1.sort_values(by=['Agency Number', "Fundind Source Name","Publication Date"], ascending=[True,True,False])
grouped_df_1 = grouped_df_1.reset_index(drop=True)

grouped_df_1

,Publication Date,Fiscal Year,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,Year 2 Revenue Amount
0,2026 05 12,2026.0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000
1,2026 02 17,2026.0,2,Mayoralty,City Funds,8.389262e+10,8.430718e+10,93996890000
2,2026 05 12,2026.0,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618
3,2026 02 17,2026.0,2,Mayoralty,Federal Grants,3.562200e+08,5.819457e+08,282942324
4,2026 05 12,2026.0,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000
...,...,...,...,...,...,...,...,...
465,2026 02 17,2026.0,943,Public Administrator-Kings County,City Funds,8.040000e+05,8.040000e+05,804000
466,2026 05 12,2026.0,944,Public Administrator-Queens County,City Funds,1.060000e+06,1.060000e+06,1060000
467,2026 02 17,2026.0,944,Public Administrator-Queens County,City Funds,1.060000e+06,1.060000e+06,1060000
468,2026 05 12,2026.0,945,Public Administrator-Richmond County,City Funds,6.500000e+04,6.500000e+04,65000
469,2026 02 17,2026.0,945,Public Administrator-Richmond County,City Funds,6.500000e+04,6.500000e+04,65000

In [11]:
# for i in grouped_df_1[catagory_columns].value_counts().items():
#     print(i)

#### Executive

In [12]:
exec_df_1 = grouped_df_1[grouped_df_1["Publication Date"] == '2026 05 12'].reset_index(drop=True).copy()

exec_df_1 = exec_df_1[catagory_columns + value_columns]

exec_df_1

,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,Year 2 Revenue Amount
0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000
1,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618
2,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000
3,2,Mayoralty,Intra-City,7.145032e+06,7.540032e+06,7542034
4,2,Mayoralty,Other Categorical Grants,5.628416e+07,5.695118e+07,76413990
...,...,...,...,...,...,...
232,941,Public Administrator-New York County,City Funds,1.600000e+06,1.600000e+06,1600000
233,942,Public Administrator-Bronx County,City Funds,5.020000e+05,5.020000e+05,502000
234,943,Public Administrator-Kings County,City Funds,8.040000e+05,8.040000e+05,804000
235,944,Public Administrator-Queens County,City Funds,1.060000e+06,1.060000e+06,1060000
236,945,Public Administrator-Richmond County,City Funds,6.500000e+04,6.500000e+04,65000

In [13]:
base_df

,Agency Number,Agency Name,Fundind Source Name
0,2,Mayoralty,City Funds
1,2,Mayoralty,Intra-City
2,2,Mayoralty,Other Categorical Grants
3,2,Mayoralty,Inter Fund Agreements
4,2,Mayoralty,Federal Grants
...,...,...,...
232,941,Public Administrator-New York County,City Funds
233,942,Public Administrator-Bronx County,City Funds
234,943,Public Administrator-Kings County,City Funds
235,944,Public Administrator-Queens County,City Funds
236,945,Public Administrator-Richmond County,City Funds

In [14]:
merged_1_df = base_df.merge(exec_df_1, how="left", on=catagory_columns).rename(columns={"Year 2 Revenue Amount":"FY27 Executive Revenue Amount"})
merged_1_df

,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,FY27 Executive Revenue Amount
0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000
1,2,Mayoralty,Intra-City,7.145032e+06,7.540032e+06,7542034
2,2,Mayoralty,Other Categorical Grants,5.628416e+07,5.695118e+07,76413990
3,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000
4,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618
...,...,...,...,...,...,...
232,941,Public Administrator-New York County,City Funds,1.600000e+06,1.600000e+06,1600000
233,942,Public Administrator-Bronx County,City Funds,5.020000e+05,5.020000e+05,502000
234,943,Public Administrator-Kings County,City Funds,8.040000e+05,8.040000e+05,804000
235,944,Public Administrator-Queens County,City Funds,1.060000e+06,1.060000e+06,1060000
236,945,Public Administrator-Richmond County,City Funds,6.500000e+04,6.500000e+04,65000

#### Prelim

In [15]:
prelim_df_1 = grouped_df_1[grouped_df_1["Publication Date"] == '2026 02 17'].reset_index(drop=True).copy()
prelim_df_1 = prelim_df_1[catagory_columns + ['Year 2 Revenue Amount']]
prelim_df_1

,Agency Number,Agency Name,Fundind Source Name,Year 2 Revenue Amount
0,2,Mayoralty,City Funds,93996890000
1,2,Mayoralty,Federal Grants,282942324
2,2,Mayoralty,Inter Fund Agreements,35000000
3,2,Mayoralty,Intra-City,7147034
4,2,Mayoralty,Other Categorical Grants,58207495
...,...,...,...,...
228,941,Public Administrator-New York County,City Funds,1600000
229,942,Public Administrator-Bronx County,City Funds,502000
230,943,Public Administrator-Kings County,City Funds,804000
231,944,Public Administrator-Queens County,City Funds,1060000
232,945,Public Administrator-Richmond County,City Funds,65000

In [16]:
merged_2_df = merged_1_df.merge(prelim_df_1, how="left", on=catagory_columns).rename(columns={"Year 2 Revenue Amount":"FY27 Prelim Revenue Amount"})
merged_2_df

,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,FY27 Executive Revenue Amount,FY27 Prelim Revenue Amount
0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000,9.399689e+10
1,2,Mayoralty,Intra-City,7.145032e+06,7.540032e+06,7542034,7.147034e+06
2,2,Mayoralty,Other Categorical Grants,5.628416e+07,5.695118e+07,76413990,5.820750e+07
3,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000,3.500000e+07
4,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618,2.829423e+08
...,...,...,...,...,...,...,...
232,941,Public Administrator-New York County,City Funds,1.600000e+06,1.600000e+06,1600000,1.600000e+06
233,942,Public Administrator-Bronx County,City Funds,5.020000e+05,5.020000e+05,502000,5.020000e+05
234,943,Public Administrator-Kings County,City Funds,8.040000e+05,8.040000e+05,804000,8.040000e+05
235,944,Public Administrator-Queens County,City Funds,1.060000e+06,1.060000e+06,1060000,1.060000e+06
236,945,Public Administrator-Richmond County,City Funds,6.500000e+04,6.500000e+04,65000,6.500000e+04

In [17]:
merged_2_df.head(10)

,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,FY27 Executive Revenue Amount,FY27 Prelim Revenue Amount
0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000,9.399689e+10
1,2,Mayoralty,Intra-City,7.145032e+06,7.540032e+06,7542034,7.147034e+06
2,2,Mayoralty,Other Categorical Grants,5.628416e+07,5.695118e+07,76413990,5.820750e+07
3,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000,3.500000e+07
4,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618,2.829423e+08
5,2,Mayoralty,State Grants,1.580727e+06,6.114443e+06,7373731,1.580727e+06
6,3,Board of Elections,City Funds,3.800000e+04,3.800000e+04,38000,3.800000e+04
7,3,Board of Elections,State Grants,0.000000e+00,2.242423e+06,0,NaN
8,4,Campaign Finance Board,City Funds,2.000000e+03,2.000000e+03,2000,2.000000e+03
9,8,Office of the Actuary,State Grants,0.000000e+00,6.300000e+04,0,0.000000e+00

In [18]:
final_df = merged_2_df.copy()

columns_to_fillna = final_df.columns[-2:]
print(columns_to_fillna)

final_df[columns_to_fillna] = final_df[columns_to_fillna].fillna(0)

final_df.head(10)

Index(['FY27 Executive Revenue Amount', 'FY27 Prelim Revenue Amount'], dtype='str')

,Agency Number,Agency Name,Fundind Source Name,Adopted Budget Amount,Current Modified Budget Amount,FY27 Executive Revenue Amount,FY27 Prelim Revenue Amount
0,2,Mayoralty,City Funds,8.389262e+10,8.790326e+10,91219217000,9.399689e+10
1,2,Mayoralty,Intra-City,7.145032e+06,7.540032e+06,7542034,7.147034e+06
2,2,Mayoralty,Other Categorical Grants,5.628416e+07,5.695118e+07,76413990,5.820750e+07
3,2,Mayoralty,Inter Fund Agreements,3.553846e+07,3.553846e+07,35000000,3.500000e+07
4,2,Mayoralty,Federal Grants,3.562200e+08,7.462306e+08,265914618,2.829423e+08
5,2,Mayoralty,State Grants,1.580727e+06,6.114443e+06,7373731,1.580727e+06
6,3,Board of Elections,City Funds,3.800000e+04,3.800000e+04,38000,3.800000e+04
7,3,Board of Elections,State Grants,0.000000e+00,2.242423e+06,0,0.000000e+00
8,4,Campaign Finance Board,City Funds,2.000000e+03,2.000000e+03,2000,2.000000e+03
9,8,Office of the Actuary,State Grants,0.000000e+00,6.300000e+04,0,0.000000e+00

In [19]:
final_df.to_excel("Docs/Collapsed_Revenues_Agency_by_Funding_Source.xlsx", index=False)

### By Agency

In [20]:
# agency_df = final_df.copy()

In [21]:
# agency_df.groupby(["Agency Number", "Agency Name"], as_index=False)[columns_to_fillna].sum().copy()

In [22]:
# final_df.to_excel("Docs/Collapsed_Revenues_by_Agency.xlsx", index=False)